name: Fetch Nakasho JSON every day

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: curl -R -z nakasho.json -o nakasho.json https://api.github.com/repos/github-nakasho/quantph/issues
      - name: Diff
        id: diff
        run: |
          git add -N .
          git diff --quiet --exit-code
        continue-on-error: true
      - name: Commit & Push
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "Update nakasho.json"
          git push
        if: steps.diff.outcome == 'failure'